<?php

require("functions.php");
require("verlag/menu_theme.php");
require_once("pages/unteraccounts_edit.inc");

function lokalkoenig_user_verlag_check_user_access_is_verlag($account){
  
  $obj = \LK\get_user($account);
  if(!$obj OR !$obj ->isVerlag()){
      return false;
  }
  
  $current = \LK\current();
  if($current -> isModerator()){
      return true;
  }
  
  if($current -> isVerlag() OR $current -> isVerlagController()){
      $test = $current -> getVerlag();
      $test2 = $obj -> getVerlag();
      
      if($test == $test2){
          return true;
      }
  }
  
  return false;
}

/**
 * Alters the Page-Variables 
 * in order to place the Ausgaben-Switcher
 * 
 * @param array $page
 */
function lokalkoenig_user_verlag_page_alter(&$page) {
  
  if(lk_search_is_searchpage() && !lk_search_has_no_results()){
    
    $current = \LK\current();
    if(!$current ->isTelefonmitarbeiter()){
      return ;
    }
    
    $query = \LK\Solr\SearchQueryParser::get();
    $ausgaben = $current ->getAusgabenFormatted();
    $link = url('user/' . $current ->getUid() . "/setplz", ['query' => $query]);
    
    $new_sidebar = [
      '#weight' => -10,
      '#markup' => theme('lk_user_change_ausgaben', [
        'ausgaben' => $ausgaben, 
        'link' => $link
      ]),
    ];
    
    array_splice($page['sidebar_first'], 1, 0, ['lokalkoenig_user_verlag' => $new_sidebar]);
  }
 }


/**
 * Restricts the Settings 
 * on the Verlags-Settings
 * 
 * @param array $form
 * @return array
 */
function lokalkoenig_user_verlag_form_alter_may_hide_plz(&$form){
    
    $current = \LK\current();
    if(!$current -> hasRight("edit plz")){
        $deny = [
         'field_vku_editor',
         'field_plz_sperre',
         'field_anzeige_des_ma_protokolls',
         'field_testverlag',
         'field_sperrung_vku',   
         'field_sperrung_vku_hinweis',
         'field_sperrung_vku_pdf',
         'field_vku_editor_dokumente',  
         'field_vku_2',   
        ];  
        
        foreach ($deny as $field){
          $form['profile_verlag'][$field]['#access'] = false;
        }
    }
    
    return $form;
}

function lokalkoenig_user_verlag_form_alter(&$form, &$form_state, $form_id) {

  if($form_id == 'user_profile_form'){
    if($form["#user_category"] == 'verlag' AND $form["#user"] -> uid) {
           $form["#process"][] = 'lokalkoenig_user_verlag_form_alter_may_hide_plz';
           drupal_add_js("var verlag_vku_vorschau_url='". url("user/" . $form["#user"] -> uid . "/testpdf") ."'", 'inline'); 
           drupal_add_js(drupal_get_path("module", 'lokalkoenig_user') ."/js/vku_vorschau.js");
    }
  }


  if($form_id == 'views_exposed_form'){
    if($form["#id"] == 'views-exposed-form-lk-log-page-1'){
      $form['uid']['#autocomplete_path'] = 'user/' . arg(1) . '/usersearch'; 
    } 
    
     if($form["#id"] == 'views-exposed-form-lk-log-page-2'){
         $form['#action'] = url(current_path());
    }     
  }
}


function lokalkoenig_user_views_query_alter(&$view, &$query)   {
  
  if($view -> name == 'last_viewed'){
     $time = time() - (60*60*24*7);
    
    if(isset($_GET["lastviewed_time"])){
        if($_GET["lastviewed_time"] == 'All') $time = 0;
        
        if($_GET["lastviewed_time"] == 2) $time = time() - (60*60*24*30);
        if($_GET["lastviewed_time"] == 3) $time = time() - (60*60*24*30*2);
        
    }
    else $time = 0;
    
    if($time){
      $query -> where[1]['conditions'][1]['field']  = 'lk_lastviewed.lastviewed_time >= ' . $time;
    }
  }
  
  if($view -> name == 'lk_log'){
    if($view->current_display == 'page_4') return ;
    if($view->current_display == 'page_5') return ;
    
    $time = time() - (60*60*24*7);
    
    if(isset($_GET["log_date"])){
        if($_GET["log_date"] == 'All') $time = 0;
        
        if($_GET["log_date"] == 2) $time = time() - (60*60*24*30);
        if($_GET["log_date"] == 3) $time = time() - (60*60*24*30*2);
    }
    
    if($time){
      $query -> where[1]['conditions'][0]['field']  = 'lk_verlag_log.log_date >= ' . $time;
    }
  }
}

function lokalkoenig_user_verlag_editaccount($verlag, $uid){
  return drupal_render(drupal_get_form('lk_user_edit_ma'));
}
