<?php

/**
 * Alter the Neuigkeiten View
 * 
 * @global type $user
 * @param type $view
 * @param type $query
 */
function lokalkoenig_user_dashboard_views_query_alter(&$view, &$query) {
global $user;
   
   if($view->name == 'neuigkeiten'){
      if(lk_is_moderator()){
          if(arg(0) == 'user' AND $user -> uid != arg(1)){
             $query->where[1]['conditions'][2]['value'][0] = arg(1);
          }
          else {
            $query->where[1]['conditions'][2]['value'][0] = 0;
            $query->where[1]['conditions'][2]['operator'] = 'not in';
          }
      }     
      else {
          $query->where[1]['conditions'][2]['value'][0] = $user -> uid;
      } 
   }
}


function lokalkoenig_user_dashboard_entity_view($entity, $type, $view_mode, $langcode) {
 
 if($type == 'neuigkeit'){
     if(lk_is_moderator() AND $entity->field_message_status['und'][0]['value'] != 'draft'):
         require_once(__DIR__ . '/pages/neuigkeit.inc');
         
          $entity->content['an'] = array(
            '#markup' => neuigkeiten_get_recivieres_stats($entity),
            '#weight' => 10,
          );
     endif;
 } 
}



/** Dashboard Links */
function _lokalkoenig_user_dashboard_links($account){
  
  $obj = \LK\get_user($account);  
  $uid = $obj -> getUid();  
  
  $links = array();
  $links[] = array('link' => "user/" . $uid . "/dashboard", 'title' => '<span class="glyphicon glyphicon-th-large"></span>&nbsp;&nbsp;Dashboard');
  $links[] = array('link' => "messages", 'title' => '<span class="glyphicon glyphicon-envelope"></span>&nbsp;&nbsp; Nachrichten');

  if($obj ->isVerlag() OR $obj -> isVerlagController()){
     $verlag_id = $obj ->getVerlag();
     $links[] = array('link' => 'user/' . $verlag_id . "/struktur", 'title' => '<span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Mitarbeiter-Accounts'); 
  }

 if(!$obj ->isAgentur()){
     $links[] = array('link' => 'user/' . $uid . "/vku", 'title' => '<span class="glyphicon glyphicon-cloud-download"></span>&nbsp;&nbsp;Verkaufsunterlagen'); 
  }
  
  if(!$obj ->isAgentur()){
     $links[] = array("title" => '<span class="glyphicon glyphicon-tag"></span>&nbsp;&nbsp; Merkliste', 'link' => "merkliste");
  }

  $links[] = array('divider' => true);
  
  $links[] = array("title" => '<span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Profil ansehen', 'link' => "user/" . $account -> uid);
  $links[] = array("title" => '<span class="glyphicon glyphicon-pencil"></span>&nbsp;&nbsp; Profildaten bearbeiten', 'link' => "user/" . $account -> uid . "/edit/main");
  $links[] = array("title" => '<span class="glyphicon glyphicon-pencil"></span>&nbsp;&nbsp; Passwort ändern', 'link' => "user/" . $account -> uid . "/edit");
  
  if($obj ->isTelefonmitarbeiter()){
    $links[] = array("title" => '<span class="glyphicon glyphicon-globe"></span>&nbsp;&nbsp; Ausgaben', 'link' => "user/" . $account -> uid . "/setplz");
  }
  
  $links[] = array("title" => '<span class="glyphicon glyphicon-stats"></span>&nbsp;&nbsp; Statistiken', 'link' => "user/" . $account -> uid . "/stats");

return $links; 
}

function lokalkoenig_user_dashboard_init(){
global $user;  
  
  if(!lk_vku_access()) { 
      return ;
  }
 
  include_once(drupal_get_path('module', 'privatemsg') . "/privatemsg.pages.inc");
  drupal_add_library('system', 'effects.shake');
  
  $support = user_load(LK_SYSTEM_USER_UID);
  $mas = _new_generate_to_options();
      
  $element = '<div class="form-type-select form-item form-group">  <label>Senden an:&nbsp;&nbsp;&nbsp; </label><select name="ma[]" multiple="multiple" data-live-search="true" data-selected-text-format="count" data-size="auto" class="selectpicker form-select" size="1">';
  while(list($key, $val) = each($mas)){
     $element .= '<optgroup label="'. $val["title"] .'">';
     
     // Check if isset
     if(isset($val["users"])):
        while(list($uid, $info) = each($val["users"])){
            $element .= '<option uname="'. $info["name"] .'" value="'. $uid .'" data-subtext="'. $info["postion"]  .'">'. $info["name"] .'</option>';
        }
     endif;
            
     $element .= '</optgroup>';
    }
  
    $element .= '<option data-divider="true"></option><option value="11" uname="'. $support -> name .'" data-content="<span class=\\\'label label-success\\\'>Lokalkönig Support</span>" data-subtext="Sie haben eine Frage?">Support</option>';
    
    $element .= '</select> </div>';  
    $element = str_replace("\n", "", $element);
  
    drupal_add_js("var sendto_kampas='". $element ."'",
       array('type' => 'inline', 'scope' => 'footer', 'weight' => 5)
    );
}


function lokalkoenig_user_dashboard_privatemsg_message_insert($message){
   
  // Node anhängen
  if(isset($message -> nid)){
    $message->field_msg_kampagnen['und'][0]['nid'] = $message -> nid;
  }
  
  if(isset($message -> nodes)){
    foreach($message -> nodes as $nid){
         $message->field_msg_kampagnen['und'][]['nid'] = $nid;
    }
  }
  
  // Neuigkeit anhängen
  if(isset($message -> neuigkeit)){
    $message->field_neuigkeit['und'][0]['target_id'] = $message -> neuigkeit;
  }
 
  if(isset($message->field_neuigkeit['und'][0]['target_id'])) {
        $nk = $message->field_neuigkeit['und'][0]['target_id'];
        
        $copy = $message->recipients;
        $grant = array();
        while(list($key, $val) = each($copy)){
            $grant[] = $val -> uid;
        }
        
        $entity = entity_load("neuigkeit", array($nk));
        $nk_entity = $entity[$nk];
        
        $existent = array();
        
        foreach( $nk_entity->field_recievers["und"] as $i){
            $existent[] = $i["uid"];
        }
        
        foreach($grant as $u){
            if(!in_array($u, $existent)){
                $nk_entity->field_recievers["und"][]['uid'] = $u;
            }
        } 
        
        $nk_entity -> save();  
  }  
 
  $copy = $message;
  reset($copy -> recipients);
 
  while(list($key, $account) = each($copy -> recipients)){
    db_query("INSERT INTO pm_tags_index SET tag_id='2', uid='". $account -> uid ."', thread_id='". $copy ->  mid ."'");
  }
}


function _new_generate_to_options($return_array = false){
    
    if($return_array AND isset( $_SESSION["user_to_data"])){
        return  $_SESSION["user_to_data"];
    }
    
    if(isset($_SESSION["user_to_data_grouped"])){
        return $_SESSION["user_to_data_grouped"];
    }
    
    $current = \LK\current();
    if(!$current){
        return array();
    }
    
    // Dont make it for thoose users 
    if($current ->isModerator() OR $current ->isAgentur()){
        return array();
    }
    
    $users = array();
    $structured = array();
    
    if($current ->isVerlag() OR $current ->isVerlagController()){
        $verlag = $current ->getVerlagObject();
        $structured[0]["title"] = 'Hauptaccounts';
        $structured[0]["users"] = array();    
        
        if($current -> isVerlagController()){
            $verlags_id = $verlag -> getUid();
            
            $structured[0]["users"][$verlags_id] = array(
               'name' => $verlag -> getUsername(),
               'postion' => $verlag ->getRole(), 
            );
            
            $users[] = $verlags_id;
        }
        
        $controller = $verlag -> getVerlagscontroller();
        foreach($controller as $uid){
            if($uid == $current -> getUid()){
                continue;
            }
            
            $obj = \LK\get_user($uid);
            if(!$obj):
                continue;
            endif;
            
            if(!$obj ->getStatus()){
                continue;
            }
            
            $structured[0]["users"][$uid] = array(
               'name' => $obj -> getUsername(),
               'postion' => $obj ->getRole(), 
            );
            
            $users[] = $uid;
        }
        
        $teams = $verlag -> getTeams();
        while(list($team_id, $team) = each($teams)){
                $leiter = $team -> getLeiter();   
            
                $structured[$team_id]["title"] = $team -> getTitle();
                $structured[$team_id]["users"] = array();
                $members = $team -> getUser();
                
                foreach($members as $member){
                    $users[] = $member;
                    $user_object = \LK\get_user($member);
                    if($user_object ->getStatus()){
                       $structured[$team_id]["users"][$member] = array(
                           'name' => $user_object ->getUsername(),
                           'postion' => $user_object ->getRole(),
                       );     
                    }
                }
        }
    }
    // MA
    else {
       $team = $current ->getTeamObject();
       if(!$team){
           return array();
       }
       
       $team_id = $team ->getId();
       $structured[$team_id]["title"] = $team -> getTitle();
       $members = $team -> getUser();
       foreach($members as $member){
          
           if($member == $current -> getUid()){
              continue;
           }
           
          $users[] = $member;
                    
          $user_object = \LK\get_user($member);
          if($user_object ->getStatus()){
             $structured[$team_id]["users"][$member] = array(
                'name' => $user_object ->getUsername(),
                'postion' => $user_object ->getRole(),
              );     
          }
       }
    }
    
     // Save this somehow
    $_SESSION["user_to_data"] = $users;
    $_SESSION["user_to_data_grouped"] = $structured;
    
    if($return_array){
        return $users;
    }
    
return $structured;    
}


function _generate_to_options($return_array = false){
   return _new_generate_to_options($return_array); 
}

function lokalkoenig_user_dashboard_menu(){

  $items['user/%user/dashboard'] = array(
      'access callback' => 'user_is_logged_in',
      'file' => 'pages/dashboard.inc',
      'page callback' => '_lokalkoenig_dashboard',
      'page arguments' => array(1),
      'title' => 'Startseite',
      'type' => MENU_CONTEXT_NONE);
  
  $items['msg/send'] = array(
      'access callback' => 'lk_vku_access',
      'file' => 'pages/send.inc',
      'page callback' => '_lokalkoenig_node_send_send',
      'title' => 'Kampagne versenden',
      'type' => MENU_CONTEXT_NONE);
   
   
  $items['notify-support'] = array(
      'access callback' => 'lk_vku_access',
      'file' => 'pages/notify_support.inc',
      'page callback' => 'notify_support_submit',
      'title' => 'Support',
      'type' => MENU_CONTEXT_NONE);
  
  $items['node/%node/send'] = array(
      'access callback' => 'lk_vku_access',
      'file' => 'pages/send.inc',
      'page callback' => '_lokalkoenig_node_send',
      'page arguments' => array(1),
      'title' => 'Kampagne versenden',
      'type' => MENU_CONTEXT_NONE);
      
      
  $items['user/%user/addnews'] = array(
      'access callback' => 'lk_vku_access',
      'file' => 'pages/neuigkeit.inc',
      'page callback' => '_lokalkoenig_neuigkeit_add',
      'page arguments' => array(1),
      'title' => 'Neuigkeit erstellen',
      'type' => MENU_CONTEXT_NONE);    
      
      
  $items['user/%user/alerts'] = array(
      'access callback' => 'lk_vku_access',
      'file' => 'pages/alerts.inc',
      'page callback' => '_lk_alerts_page',
      'page arguments' => array(1),
      'title' => 'Alerts verwalten',
      'type' => MENU_CONTEXT_NONE);        
      
      
  $items['user/%user/neuigkeiten/%'] = array(
      'access callback' => true,
      'file' => 'pages/neuigkeit.inc',
      'page callback' => '_lokalkoenig_neuigkeit_show',
      'page arguments' => array(1, 3),
      'title' => 'Neuigkeit',
      'type' => MENU_CONTEXT_NONE);  
      
   $items['user/%user/neuigkeiten/%/edit'] = array(
      'access callback' => true,
      'file' => 'pages/neuigkeit.inc',
      'page callback' => '_lokalkoenig_neuigkeit_edit',
      'page arguments' => array(1, 3),
      'title' => 'Neuigkeit',
      'type' => MENU_CONTEXT_NONE);     
      
      
  $items['neuigkeiten/%'] = array(
      'access callback' => true,
      'file' => 'pages/neuigkeit.inc',
      'page callback' => '_lokalkoenig_neuigkeit_show_redirect',
      'page arguments' => array(1),
      'title' => 'Neuigkeit',
      'type' => MENU_CONTEXT_NONE);            
   
   $items['suchanfrage'] = array(
      'access callback' => 'lk_vku_access',
      'file' => 'pages/suchanfrage.inc',
      'page callback' => '_lk_suchanfrage',
      'title' => 'Suchanfrage',
      'type' => MENU_CONTEXT_NONE);       
      
      

return $items;
}

function lk_redirect_to_dash($form, &$form_state){
   $user = user_load($form_state['uid']);
   $form_state['redirect'] = 'user/' . $user->uid . "/dashboard";
}

  
function lokalkoenig_user_dashboard_form_alter(&$form, &$form_state, $form_id){
  if($form_id == "user_login"){
      $form["#submit"][] = 'lk_redirect_to_dash';
  }
  
  if($form_id == 'eck__entity__form_add_neuigkeit_neuigkeit'){
    require_once(drupal_get_path('module', 'lokalkoenig_user') . '/pages/neuigkeit.inc');
    neuigkeit_form_alter($form, $form_state);
  }
  
  if($form_id == 'eck__entity__form_edit_neuigkeit_neuigkeit'){
    require_once(drupal_get_path('module', 'lokalkoenig_user') .'/pages/neuigkeit.inc');
    neuigkeit_form_alter($form, $form_state);
  }
}

function lokalkoenig_user_dashboard_theme(){

 $themes = array ('lk_ma_dashboard' => array(
            'template' => 'templates/lk_ma_dashboard', // your template file called custompage.tpl.php
            'variables' => array(
              'list' => array(),
              'account' => NULL
            ),
        ),
    );

 $themes["neuigkeiten_admin"] = array(
            'template' => 'templates/neuigkeiten_admin', // your template file called custompage.tpl.php
            'variables' => array(
              'entity' => NULL,
              'message' => NULL
            ),
        );
        
  $themes["neuigkeiten_status"] = array(
            'template' => 'templates/neuigkeiten_status', // your template file called custompage.tpl.php
            'variables' => array(
              'entity' => NULL
            ),
        );     
        
   $themes["alerts_overview"] = array(
            'template' => 'templates/alerts_overview', // your template file called custompage.tpl.php
            'variables' => array(
              'alerts' => NULL,
              'account' => NULL
            ),
        );             

return $themes;
}

?>