<?php

function lokalkoenig_user_stats_menu(){
  $items = array();
  $items['user/%user/stats'] = array(
      'access callback' => 'lk_vku_access',
      'access arguments' => array(1),
      'page callback' => 'lokalkoenig_user_stats_page',
      'page arguments' => array(1),
      'title' => 'Statistiken',
      'type' => MENU_CONTEXT_NONE);

  $items['user/%user/verlagstats'] = array(
      'access callback' => 'lk_verlagsaccount_access',
      'access arguments' => array(1),
      'page callback' => 'lokalkoenig_user_stats_page_verlag',
      'page arguments' => array(1),
      'title' => 'Verlags-Statistiken',
      'type' => MENU_CONTEXT_NONE);
  
  $items['user/%user/abrechnung'] = array(
      'access callback' => 'lk_verlagsaccount_access',
      'access arguments' => array(1),
      'page callback' => 'lokalkoenig_user_stats_page_abrechnung',
      'page arguments' => array(1),
      'file' => 'pages/verlag_abrechnung.inc',
      'title' => 'Abrechnung',
      'type' => MENU_CONTEXT_NONE);

  $items['user/%user/agenturabrechnung'] = array(
      'access callback' => 'lk_agenturabrechnung_access',
      'access arguments' => array(1),
      'page callback' => 'lokalkoenig_user_stats_agenturabrechnung',
      'page arguments' => array(1),
      'file' => 'pages/verlag_abrechnung.inc',
      'title' => 'Abrechnung',
      'type' => MENU_CONTEXT_NONE);


return $items;
}

function lokalkoenig_user_stats_page_alter(&$page){
  // logging users time spent sessions & hits

  $current = \LK\current();
  if($current) {
    $tracker = new \LK\Stats\TimeTracker();
    $tracker->track($current);
  }
}


function lk_agenturabrechnung_access($agentur){
  $current = \LK\current();  
  $account = \LK\get_user($agentur);
  
  if(!$account -> isAgentur()){
      return false;
  }
  
  if($current == $account OR $current -> isModerator()){
      return true;
  }
  
return false;
}


function lokalkoenig_user_stats_page_verlag($verlag){
  $stats = new \LK\Stats\Views\StatsViewer('verlag', $verlag -> uid);

  return $stats->render();
}


function lk_verlagsaccount_access($account){
  $accessed = \LK\get_user($account -> uid);
  if(!$accessed ->isVerlag()){

    return FALSE;
  }

  $current = \LK\current();
  if($current ->isModerator()){

    return TRUE;
  }

  if($current ->isVerlagController() OR $current ->isVerlag()){
      $verlag = $current ->getVerlag();
      if($verlag == $accessed ->getUid()){

        return TRUE;
      }
  }

  return FALSE;
}


function lokalkoenig_user_stats_page($account){
   
  $obj = \LK\get_user($account);
  if(!$obj OR $obj ->isAgentur()){
    drupal_goto("user");
  }

  $stats = new \LK\Stats\Views\StatsViewer('user', $account -> uid);

  return $stats->render();
}
