<?php

require("functions.php");
require("verlag/menu_theme.php");
require_once("pages/unteraccounts_edit.inc");

function lokalkoenig_user_verlag_check_user_access_is_verlag($account){
  
  $obj = \LK\get_user($account);
  if(!$obj OR !$obj ->isVerlag()){
      return false;
  }
  
  $current = \LK\current();
  if($current -> isModerator()){
      return true;
  }
  
  if($current -> isVerlag() OR $current -> isVerlagController()){
      $test = $current -> getVerlag();
      $test2 = $obj -> getVerlag();
      
      if($test == $test2){
          return true;
      }
  }
  
  return false;
}

function lokalkoenig_user_verlag_form_alter_may_hide_plz(&$form){
    $current = \LK\current();
    if(!$current -> hasRight("edit plz")){
        $form['profile_verlag']['field_plz_sperre']['#access'] = false;
        $form['profile_verlag']['field_anzeige_des_ma_protokolls']['#access'] = false;
        $form['profile_verlag']['field_sperrung_vku']['#access'] = false;
        $form['profile_verlag']['field_testverlag']['#access'] = false;
        $form['profile_verlag']['field_sperrung_vku_hinweis']['#access'] = false;
        $form['profile_verlag']['field_sperrung_vku_pdf']['#access'] = false;

    }
    
    return $form;
}

function lokalkoenig_user_verlag_form_alter(&$form, &$form_state, $form_id) {

  if($form_id == 'user_profile_form'){
    if($form["#user_category"] == 'verlag' AND $form["#user"] -> uid) {
           $form["#process"][] = 'lokalkoenig_user_verlag_form_alter_may_hide_plz';
           drupal_add_js("var verlag_vku_vorschau_url='". url("user/" . $form["#user"] -> uid . "/testpdf") ."'", 'inline'); 
           drupal_add_js(drupal_get_path("module", 'lokalkoenig_user') ."/js/vku_vorschau.js");
    }
  }


  if($form_id == 'views_exposed_form'){
    if($form["#id"] == 'views-exposed-form-lk-log-page-1'){
      $form['uid']['#autocomplete_path'] = 'user/' . arg(1) . '/usersearch'; 
    } 
    
     if($form["#id"] == 'views-exposed-form-lk-log-page-2'){
         $form['#action'] = url(current_path());
    }     
  }
}


function lokalkoenig_user_views_query_alter(&$view, &$query)   {
  
  if($view -> name == 'last_viewed'){
     $time = time() - (60*60*24*7);
    
    if(isset($_GET["lastviewed_time"])){
        if($_GET["lastviewed_time"] == 'All') $time = 0;
        
        if($_GET["lastviewed_time"] == 2) $time = time() - (60*60*24*30);
        if($_GET["lastviewed_time"] == 3) $time = time() - (60*60*24*30*2);
        
    }
    else $time = 0;
    
    if($time){
      $query -> where[1]['conditions'][1]['field']  = 'lk_lastviewed.lastviewed_time >= ' . $time;
    }
  }
  
  if($view -> name == 'lk_log'){
    if($view->current_display == 'page_4') return ;
    if($view->current_display == 'page_5') return ;
    
    $time = time() - (60*60*24*7);
    
    if(isset($_GET["log_date"])){
        if($_GET["log_date"] == 'All') $time = 0;
        
        if($_GET["log_date"] == 2) $time = time() - (60*60*24*30);
        if($_GET["log_date"] == 3) $time = time() - (60*60*24*30*2);
    }
    
    if($time){
      $query -> where[1]['conditions'][0]['field']  = 'lk_verlag_log.log_date >= ' . $time;
    }
  }
}

function lokalkoenig_user_verlag_editaccount($verlag, $uid){
  return drupal_render(drupal_get_form('lk_user_edit_ma'));
}
