<?php

/**
 * Autoloader
 */
require_once __DIR__ .'/../src/autoload.php';
require_once __DIR__ .'/views/schema.inc';
require_once __DIR__ .'/cron/cronjobs.inc';
require_once __DIR__ .'/depricated.inc.php';
require_once __DIR__ .'/blocks.inc.php';
require_once __DIR__ .'/roles.inc.php';
require_once __DIR__ .'/lokalkoenig_admin.menu.inc';

/**
 * HOOK_INT
 * @global type $user
 */
function lokalkoenig_admin_init(){
global $user;    

  if(arg(0) == "backoffice"){
    lk_set_icon('cog');
    drupal_add_css(drupal_get_path('theme', 'bootstrap_lk') .'/dist/admin.css');
  }   

  // Takeover
  if(arg(0) == 'user'){
    if($user -> uid == 0){
      drupal_set_title("Anmelden");
       lk_set_icon('home');
    }
    else {
      lk_set_icon('user');
      drupal_set_title("Ihr Profil");
    }
  }
}


/**
 * Sets the Param "field_kamp_suche" as default value on the 
 * in the page admin/structure/computed_field_recompute
 * 
 * @param type $form
 * @param type $form_state
 * @param type $form_id
 */
function lokalkoenig_admin_form_alter(&$form, &$form_state, $form_id){
  
  if($form_id == 'computed_field_tools_recompute_form'){
    $form['fields']['computed_field_to_recompute']['#default_value'] = 'field_kamp_suche';
    $form["entities"]['#access'] = false; 
  }
  
  if(arg(0) == "backoffice" && arg(1) === 'kampagnen' && $form_id == 'views_exposed_form' && isset($form["field_kamp_status_value"])){
    unset($form["field_kamp_status_value"]["#size"]);
    $form["field_kamp_status_value"]["#type"] = 'select';
    $form["field_kamp_status_value"]["#options"] = [
     '' => "-- ALLE --",
     'new' => "Neu",
     'proof' => "Zu überprüfen",
     'published' => "Online",
     'canceled' => "Abgelehnt"
    ];
  }  
}
