<?php

$_lk_faq_node = NULL;
$_lk_subtitle = NULL;
$_lk_icon = NULL;

/** 
 * Adding a comment 
 *  And more
 **/

require_once("pathtitle.inc.php");

function lk_get_subtitle(){
    return $GLOBALS["_lk_subtitle"];
}

function lk_set_subtitle($subtitle = NULL){
global $_lk_subtitle;
  $_lk_subtitle = $subtitle;
}

function lk_set_icon($icon = NULL){
global $_lk_icon;

  $_lk_icon = $icon;
}

function lk_set($pagetitle, $subtitle, $icon, $faq_id = NULL){
   lk_set_faq($faq_id);
   drupal_set_title($pagetitle);
   lk_set_subtitle($subtitle);
   lk_set_icon($icon);
}

function lokalkoenig_init(){
global $user; 
   if(arg(0) == 'user'){
      lk_set_faq(6);
      
      
      if($user -> uid == 0){
        drupal_set_title("Anmelden");
         lk_set_icon('home');
      }
      else {
        lk_set_icon('user');
        drupal_set_title("Ihr Profil");
        //lk_set_subtitle('Verwalten Sie hier Ihre Daten');
      }
      
   }
}


function lokalkoenig_block_info(){

 $blocks['lokalkoenig_title'] = array(
    // info: The name of the block.
    'info' => 'Block: Title der Seite',
    // Block caching options (per role, per user, etc.)
  );
  
  
  $blocks['lokalkoenig_logos_unten'] = array(
    // info: The name of the block.
    'info' => 'LK: Logos Unten',
    'cache' => DRUPAL_CACHE_GLOBAL
    // Block caching options (per role, per user, etc.)
  );
  
  
  $blocks['lokalkoenig_help'] = array(
    'info' => 'Block: Hilfe-Seite',
  ); 

return $blocks;
}


function lkgetusername(){
global $user;

  if($user -> uid == 0) return 'Anonymus';
 
  $profile = profile2_load_by_user($user);
  
  if(isset($profile['main']->field_profile_vorname['und'][0]['safe_value'])){
     return $profile['main']->field_profile_vorname['und'][0]['safe_value'] . " " . $profile['main']->field_profile_name['und'][0]['safe_value'];   
  }
  
  
return 'No Name';
}


function lokalkoenig_block_view($delta = '') {
global $user, $_lk_subtitle, $_lk_icon, $_lk_faq_node;
  
  
  
  $block = array();
  
  if($delta == 'lokalkoenig_logos_unten'){
      drupal_add_js('sites/all/themes/bootstrap_lk/owlcarousel/owl.carousel.min.js');
      drupal_add_css('sites/all/themes/bootstrap_lk/owlcarousel/owl.carousel.css');
      drupal_add_css('sites/all/themes/bootstrap_lk/owlcarousel/owl.theme.css');
      
      $return = '<div class="logos_verlage owl-carousel">';  
      
      $dbq = db_query("SELECT nid FROM node WHERE type='logo' AND status='1' ORDER BY RAND()");
      foreach($dbq as $all){
        $node = node_load($all -> nid);
        //dpm($node);
        //
        $img =image_style_url('verlags-logos-footer', $node -> field_logo['und'][0]['uri']);
        $return .= '<div><img src="'. $img . '" title="'. $node -> title .'" /></div>';
      
      }
        
      $return .= '</div>'; 
    
      return array('content' => $return);
  }
  
  
 
  
  if($delta == 'lokalkoenig_title'){
    $content = '<div class="page-header">';
    
    if((arg(0) == 'merkliste3' AND arg(1)) OR (arg(0) == "node" AND $node = node_load(arg(1)) AND $node -> type == 'kampagne' AND !arg(2))){
      $content .=  '<div class="pull-right" style="margin-top: 0px; font-size: 2em;"><a href="javascript:history.back()" style="font-size: 0.7em; color: White;">Zurück <span class="glyphicon glyphicon-chevron-right"></span></a></div>';
    }
    $content .= '<h2>';
    
   $title = drupal_get_title();
    
    if($user -> uid != 0){
      if(arg(0) == "user" AND !arg(2) AND $account = user_load(arg(1)) AND $account -> uid != 0){
        //$title = lk_get_username_and_role($account); 
      }
    }
    
    if(arg(0) == "node" AND $node = node_load(arg(1)) AND !arg(2)){
    
      
      if($node -> type == 'kampagne' AND $node -> status == 1){
        $title = 'Detailansicht'; 
        $content .= '<span class="glyphicon glyphicon-plus"></span> ';
      }
    }
    
    if($_lk_icon){
      $content .= '<span class="glyphicon glyphicon-'. $_lk_icon .'"></span> ';
    }  
      
    $content .= $title;
    
    if($_lk_subtitle){
      $content .= ' <small>' . $_lk_subtitle . '</small>';
    }
    
    $content .= '</h2></div>';
    
    return array('content' => $content);
  }
}  



?>