<?php
require_once __DIR__ . "/lokalkoenig_search.theme.inc";
require_once __DIR__ . "/lokalkoenig_search.block.inc";

function lokalkoenig_search_search_api_data_type_info() {
  return array(
    // You can use any identifier you want here, but it makes sense to use the
    // field type name from schema.xml.
    'edge_n2_kw_text' => array(
      'name' => 'LK-FULLTEXT',
      'fallback' => 'text_und',
      // Dynamic field "supert_*".
      //'prefix' => 'textde',
      // Fulltext types are always multi-valued.
      'always multiValued' => TRUE,
    ),
  );
}

function _lk_get_recomend_count(){
  
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
  ->entityCondition('bundle', 'kampagne')
  ->propertyCondition('status', 1);
  
  $query->count();
  $query -> propertyCondition('sticky', 1);          
  $count = $query->execute();
 
  return $count;
}

function lokalkoenig_search_init(){
  if(in_array(arg(0), array("suche",'suche-grid', 'merkliste'))){
      pathtitle('search');
      $path = drupal_get_path('module', 'lokalkoenig_search');
      drupal_add_css($path . '/css/lk_search.css');
  }
  
  if(in_array(arg(2), array('searches'))){
     lk_set_icon('th-large'); 
  }
}


/**
 * If the current page is the Search-Page
 * 
 * @return boolean
 */
function lk_search_is_searchpage(){
  
  if(in_array(arg(0), array('suche', "suche-grid"))) {
    return true;
  }
  
return false;  
}

function lokalkoenig_search_preprocess_page(&$variables){
  
  if(lk_search_has_no_results()):
    unset($variables['page']['sidebar_first']);
    $variables['page']['content']['system_main']['#access'] = FALSE;
  
  endif;  
}

function lokalkoenig_search_preprocess_html(&$variables){
  
  if(lk_search_has_no_results()):
    $variables['classes_array'][] = 'no-sidebars';
  endif;   
}

/**
 * Gets back TRUE when the Search has no result
 * 
 * @return boolean
 */
function lk_search_has_no_results(){
  
  if(!lk_search_is_searchpage()) {
    return false;
  }
  if(!isset($GLOBALS['pager_total_items'][0])) {
    return false;
  }
  
  if(($GLOBALS['pager_total_items'][0] != 0)) {
    return false;
  }
  
return true;    
}


function lk_save_current_search(){
global $user;

 if(isset($_GET["search_api_views_fulltext"]) AND strlen($_GET["search_api_views_fulltext"]) > 2 AND !lk_search_has_no_results()){
              $search = _lk_get_search_options_array();
              
              $insert = array();
              $insert["uid"] = $user -> uid;
              $insert["created"] = time();
              $insert["search_string"] = $_GET["search_api_views_fulltext"];
              $insert["search_text"] = serialize($search);
              $insert["search_count"] = $GLOBALS['pager_total_items'][0];
            
            //When the User searched 
            if(isset($_SESSION["lksearch"][$_GET["search_api_views_fulltext"]])){
              $id = $_SESSION["lksearch"][$_GET["search_api_views_fulltext"]];
              db_update('lk_search_history')->fields($insert)->condition('id', $id)->execute();            
            }
            else {
              $id = db_insert('lk_search_history')->fields($insert)->execute();            
              $_SESSION["lksearch"][$_GET["search_api_views_fulltext"]] = $id;
            }
  } 
}



function form_lk_no_results($form, $form_state, $searchword){
  
  $form["#action"] = url("notify-support", array("query" => array("page" => current_path())));
  
  $form['subject'] = array(
    '#type' => 'textfield', 
    '#title' => ('Betreff'), 
    '#default_value' => 'Keine Ergebnisse für "'. $searchword .'"', 
    '#size' => 60, 
    '#maxlength' => 128, 
    '#required' => TRUE
  );

  $url = url(current_path(), array("query" => $_GET, "absolute" => true));

  $ersetzen = array(
    '[!url]' => $url
  );
  
  $form['text'] = array(
    '#type' => 'textarea', 
    '#title' => ('Nachricht'), 
    '#rows' => 10,
    '#default_value' => strip_tags(t(variable_get('lk_search_noresult', ''), $ersetzen)), 
    '#required' => TRUE
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Abschicken',
  );
    
return $form;
}


function lokalkoenig_search_form_alter(&$form, &$form_state, $form_id){
 
   if(arg(0) == 'suche' OR arg(0) == "suche-grid"){
    if($form_id == 'views_exposed_form'){
       $form["#attributes"]["class"][] = 'well lk_search_text';
       $form['submit']['#value'] = t('Search');
       $form['help'] = array('#weight' => -20, '#markup' => '<div><b><span class="glyphicon glyphicon-chevron-right"></span> Hilfe zur Suche</b><span style="display: none;">'. variable_get('lk_search_help', '') .'</span></div>');
    }
   }
}
