<?php

require_once __DIR__ . "/lokalkoneig_merkliste.menu.inc";
require_once __DIR__ . "/lokalkoenig_merkliste.blocks.inc";
require_once __DIR__ . "/views/views_data.inc";

/**
 * HOOK_init
 */
function lokalkoenig_merkliste_init(){
  
  $current = \LK\current();
  if(!$current || $current ->isAgentur()){
    return ;
  }
  
  $categories = \LK\Merkliste\UserMerkliste::getMerklisten();
  drupal_add_js(['merkliste' => ['categories' => $categories]], ['type' => 'setting']);
  drupal_add_js(drupal_get_path('module', 'lokalkoenig_merkliste') .'/js/merkliste.js', 'file');
}

/**
 * HOOK_theme
 *
 * @return array
 */
function lokalkoenig_merkliste_theme(){
  $themes = array();

  $themes["lk_merkliste_block_nav"] = [
    'template' => 'templates/lk_merkliste_block_nav',
    'variables'=> ['count_ml' => 0, 'count_lv' => 0],
  ];

  $themes["lk_merkliste_actions"] = [
    'template' => 'templates/lk_merkliste_actions',
    'variables'=> ['term' => NULL],
  ];

  $themes["lk_merkliste_navigation"] = [
    'template' => 'templates/lk_merkliste_navigation', // your template file called custompage.tpl.phü
    'variables'=> array('links' => [])
  ];

  return $themes;
}            

/**
 * HOOK_search_api_solr_query_alter
 *
 * @global stdClass $user
 * @global array $preserv_fs
 * @param array $query
 * @param array $snd
 */
function lokalkoenig_merkliste_search_api_solr_query_alter($query, $snd) {
global $user, $preserv_fs;

  if(lk_is_agentur()){
    $query['params']['fq'][1] = 'is_author:"'. $user -> uid .'"';
  }

  if($preserv_fs){
    if(is_array($preserv_fs)){
      foreach($preserv_fs as $item){
        $query['params']['fq'][] = 'im_' . $item;
      }
    }
  }

  // Need to Delete, because of visibility issues
  if(isset($query['params']['fq'][1]) && $query['params']['fq'][1] == 'is_status:"1"'){
    unset($query['params']['fq'][1]);
  } 
}

/**
 * Loads ML to the Kampagne
 * HOOK_kampagne_load
 *
 * @param \stdClass $node
 */
function lokalkoenig_merkliste_kampagne_load($node){
  
  $current = \LK\current();
  $node -> merkliste = false;   
  
  if(!$current || $current ->isAgentur()){
    return ;
  }
  
  $kampagnen = \LK\Merkliste\UserMerkliste::getKampagnen();
  if(in_array($node -> nid, $kampagnen)){
    $node -> merkliste = true;
    $node -> merkliste_id = 1;
    $node -> merkliste_terms = '';
    $node -> merkliste_title = '';
  }
}

/**
 * Alters the insert of a message with Nodes
 * HOOK_privatemsg_message_insert
 *
 * @param stdClass $message
 */
function lokalkoenig_merkliste_privatemsg_message_insert($message){  
  if(isset($message -> nids)){
    foreach($message -> nids as $nid){
      $message->field_msg_kampagnen['und'][]['nid'] = $nid;
    }
  }
}

/**
 * Alters the Message-Form, to add a ML
 * HOOK_form_alter
 *
 * @param array $form
 * @param array $form_state
 * @param string $form_id
 */
function lokalkoenig_merkliste_form_alter(&$form, &$form_state, $form_id){

  if($form_id === 'views_exposed_form' && isset($form_state['view']) && $form_state['view'] -> name === 'last_viewed'){
    $form['#prefix'] =
        '<a href="'. url('history/flush') .'" optintitle="Verlauf wirklich zurücksetzen" optin="Sind Sie sicher, dass Sie den kompletten Verlauf unwideruflich löschen möchten?" class="optindelete pull-right btn btn-success">
            <span class="glyphicon glyphicon-chevron-right"></span> Verlauf zurücksetzen
        </a>
        <h4>Zuletzt angesehene Kampagnen</h4>'
        . '<p>Hier sehen Sie Ihren Verlauf der aufgerufenen Kampagnen.</p>';
  }

  if($form_id == 'privatemsg_new' && isset($_GET["ml"])){
    $manager = new \LK\Merkliste\UserMerkliste();
    $merkliste = $manager->loadMerkliste($_GET["ml"]);

    if(!$merkliste){
      return ;
    }
    
    $kampagnen = $merkliste ->getKampagnen();
    $form['subject']['#default_value'] = 'Merkliste: ' . $merkliste ->getName(); 
    $sample = $form['field_msg_kampagnen']['und'][0];
    $x = 0;
    foreach($kampagnen as $nid){
      $form['field_msg_kampagnen']['und'][$x] = $sample;
      $form['field_msg_kampagnen']['und'][$x]['nid']['#default_value'] = $nid;    
      $x++;
    }
  }  
}
