<?php
/**
 * @file 
 * VKU-Editor-Module
 */

require_once __DIR__ . '/editor.inc';
require_once __DIR__ . '/vku_editor.field_widget.php';

/**
 * Implements a Hook
 * 
 * @param array $modules
 */
function vku_editor_vku2_add_module(){

  $current = \LK\current();
  if(!$current ->isModerator()){
    return [];
  }

  drupal_add_library('vku_editor', 'vku_inlace_editor');
  drupal_add_js(drupal_get_path('module', 'vku_editor'). '/js/ma_controller.js');

  return [
    'vku_documents' => '\\LK\\VKU\\Editor\\VKU2Handler',
  ]; 
}